export const touristAttractions2 = [
  {
    id: "1",
    name: "Kakamega Forest Reserve",
    description:
      "Kenya's last remaining tropical rainforest, home to over 400 bird species and unique wildlife including the rare De Brazza's monkey.",
    image: "/Kakamega Forest.webp",
    location: "Kakamega County",
    distance: "45 km from hotel",
    duration: "Full day trip",
    highlights: [
      "Bird watching",
      "Nature walks",
      "Canopy walks",
      "Wildlife photography",
    ],
    rating: 4.8,
  },
  {
    id: "2",
    name: "Webuye Falls",
    description:
      "Spectacular waterfalls cascading down rocky cliffs, perfect for photography and nature lovers seeking tranquil moments.",
    image: "/Webuye Falls.webp",
    location: "Bungoma County",
    distance: "35 km from hotel",
    duration: "Half day trip",
    highlights: ["Waterfall views", "Photography", "Picnic spots", "Swimming"],
    rating: 4.6,
  },
  {
    id: "3",
    name: "Maragoli Hills",
    description:
      "Scenic hills offering stunning panoramic views, perfect for hiking and experiencing the beautiful landscapes of Vihiga.",
    image: "/Maragoli Hills.webp",
    location: "Vihiga County",
    distance: "15 km from hotel",
    duration: "Half day trip",
    highlights: [
      "Scenic beauty",
      "Hiking trails",
      "Local culture",
      "Fresh air",
    ],
    rating: 4.5,
  },
  {
    id: "4",
    name: "Crying Stone of Ilesi",
    description:
      "Mysterious rock formation that appears to 'cry' water, steeped in local folklore and offering panoramic views of the region.",
    image: "/Crying Stone.webp",
    location: "Vihiga County",
    distance: "25 km from hotel",
    duration: "Half day trip",
    highlights: [
      "Cultural significance",
      "Photography",
      "Panoramic views",
      "Local legends",
    ],
    rating: 4.4,
  },
  {
    id: "5",
    name: "Masinde Muliro Gardens",
    description:
      "Beautiful botanical gardens featuring diverse plant species, perfect for leisurely walks and family outings.",
    image: "/Muliro Gardens.webp",
    location: "Kakamega Town",
    distance: "40 km from hotel",
    duration: "Half day trip",
    highlights: [
      "Botanical diversity",
      "Family friendly",
      "Peaceful walks",
      "Educational tours",
    ],
    rating: 4.3,
  },
  {
    id: "6",
    name: "Malava Forest",
    description:
      "Indigenous forest reserve offering hiking trails, bird watching opportunities, and a chance to experience Kenya's natural heritage.",
    image: "/Kakamega Forest.webp", // Using Kakamega Forest image as a suitable substitute
    location: "Kakamega County",
    distance: "50 km from hotel",
    duration: "Full day trip",
    highlights: [
      "Forest hiking",
      "Bird species",
      "Indigenous trees",
      "Conservation education",
    ],
    rating: 4.7,
  },
];

export const touristAttractions = [
  {
    id: "1",
    name: "Kakamega Forest Reserve",
    description:
      "Kenya's last remaining tropical rainforest, home to over 400 bird species and unique wildlife including the rare De Brazza's monkey.",
    longDescription:
      "Kakamega Forest Reserve stands as Kenya's last remaining tropical rainforest, a precious ecosystem that has survived for millions of years. This 238-square-kilometer forest is a biodiversity hotspot, home to over 400 bird species, 400 butterfly species, and numerous mammals including the rare De Brazza's monkey, giant forest hog, and various antelope species. The forest offers an incredible canopy walk experience, allowing visitors to walk among the treetops and observe wildlife from a unique perspective. The reserve also holds significant cultural importance to the local Luhya community, with sacred sites and traditional medicine plants scattered throughout.",
    image: "/Kakamega Forest.webp",
    gallery: [
      "/Kakamega Forest.webp",
      "/Corridor.webp",
      "/Tent.webp",
      "/Customers 21.webp",
    ],
    location: "Kakamega County",
    distance: "45 km from hotel",
    duration: "Full day trip",
    bestTime: "Early morning (6:00 AM - 10:00 AM)",
    entryFee: "KES 500 for adults, KES 200 for children",
    highlights: [
      "Bird watching",
      "Nature walks",
      "Canopy walks",
      "Wildlife photography",
      "Butterfly watching",
      "Cultural tours",
    ],
    activities: [
      "Guided nature walks through pristine forest trails",
      "Canopy walk experience 30 meters above ground",
      "Bird watching with over 400 species to spot",
      "Butterfly identification tours",
      "Photography workshops",
      "Cultural visits to local communities",
      "Medicinal plant tours with local guides",
    ],
    facilities: [
      "Visitor center",
      "Guided tours",
      "Parking",
      "Restrooms",
      "Picnic areas",
      "Gift shop",
    ],
    whatToBring: [
      "Comfortable walking shoes",
      "Binoculars",
      "Camera",
      "Water bottle",
      "Insect repellent",
      "Light jacket",
    ],
    rating: 4.8,
    reviews: 156,
    difficulty: "Easy to Moderate",
    groupSize: "2-15 people",
  },
  {
    id: "2",
    name: "Webuye Falls",
    description:
      "Spectacular waterfalls cascading down rocky cliffs, perfect for photography and nature lovers seeking tranquil moments.",
    longDescription:
      "Webuye Falls is one of Western Kenya's most spectacular natural wonders, featuring a series of cascading waterfalls that plunge dramatically down rocky cliffs into crystal-clear pools below. The falls are surrounded by lush tropical vegetation and offer multiple viewing points for photography enthusiasts. The site provides a perfect escape from the hustle and bustle of city life, with the soothing sounds of rushing water creating a meditative atmosphere. Visitors can enjoy swimming in the natural pools (during appropriate seasons), hiking along well-maintained trails, and picnicking in designated areas with stunning views of the falls.",
    image: "/Webuye Falls.webp",
    gallery: [
      "/Webuye Falls.webp",
      "/Hero 1.webp",
      "/Customers 12.webp",
      "/Customers 1.webp",
    ],
    location: "Bungoma County",
    distance: "35 km from hotel",
    duration: "Half day trip",
    bestTime: "Morning (8:00 AM - 12:00 PM)",
    entryFee: "KES 300 for adults, KES 150 for children",
    highlights: [
      "Waterfall views",
      "Photography",
      "Picnic spots",
      "Swimming",
      "Hiking trails",
      "Rock climbing",
    ],
    activities: [
      "Waterfall viewing from multiple vantage points",
      "Swimming in natural pools (seasonal)",
      "Photography sessions at golden hour",
      "Hiking along forest trails",
      "Rock climbing for adventure seekers",
      "Picnicking with waterfall views",
      "Nature meditation sessions",
    ],
    facilities: [
      "Parking area",
      "Picnic tables",
      "Basic restrooms",
      "Walking trails",
      "Viewing platforms",
    ],
    whatToBring: [
      "Swimming gear",
      "Waterproof camera",
      "Hiking boots",
      "Picnic supplies",
      "Sunscreen",
      "First aid kit",
    ],
    rating: 4.6,
    reviews: 89,
    difficulty: "Easy",
    groupSize: "2-20 people",
  },
  {
    id: "3",
    name: "Maragoli Hills",
    description:
      "Scenic hills offering stunning panoramic views, perfect for hiking and experiencing the beautiful landscapes of Vihiga.",
    longDescription:
      "The Maragoli Hills are a prominent feature of the Vihiga landscape, offering breathtaking views and excellent hiking opportunities. The hills are steeped in the culture and history of the Maragoli people. A hike to the top provides a rewarding experience with panoramic vistas of the surrounding green countryside, making it a favorite spot for both locals and tourists seeking a peaceful escape into nature and a bit of exercise.",
    image: "/Maragoli Hills.webp",
    gallery: [
      "/Maragoli Hills.webp",
      "/Customers 11.webp",
      "/Customers 9.webp",
      "/Customers 7.webp",
    ],
    location: "Vihiga County",
    distance: "15 km from hotel",
    duration: "Half day trip",
    bestTime: "Mid-morning (9:00 AM - 1:00 PM)",
    entryFee: "KES 200 for adults, KES 100 for children",
    highlights: [
      "Scenic beauty",
      "Hiking trails",
      "Local culture",
      "Fresh air",
      "Panoramic Views",
      "Village visits",
    ],
    activities: [
      "Scenic hike through local trails",
      "Cultural village visits",
      "Photography of pristine landscapes",
      "Bird watching",
    ],
    facilities: ["Village guides", "Basic parking", "Community center"],
    whatToBring: ["Hiking shoes", "Camera", "Water bottle", "Snacks"],
    rating: 4.5,
    reviews: 67,
    difficulty: "Easy to Moderate",
    groupSize: "2-12 people",
  },
  {
    id: "4",
    name: "Crying Stone of Ilesi",
    description:
      "Mysterious rock formation that appears to 'cry' water, steeped in local folklore and offering panoramic views of the region.",
    longDescription:
      "The Crying Stone of Ilesi is one of Western Kenya's most intriguing natural monuments, a massive rock formation that continuously 'weeps' water from its surface, creating an almost mystical atmosphere. According to local Luhya folklore, the stone represents a woman who was turned to stone while crying for her lost children. The geological phenomenon occurs due to underground springs that seep through the porous rock, creating the appearance of tears. From the top of the stone, visitors enjoy breathtaking panoramic views of the surrounding countryside, including tea plantations, rural homesteads, and rolling hills. The site has become a pilgrimage destination for both locals and tourists seeking to understand the rich cultural heritage of the region.",
    image: "/Crying Stone.webp",
    gallery: [
      "/Crying Stone.webp",
      "/Top View.webp",
      "/Building 1.webp",
      "/Gate.webp",
    ],
    location: "Vihiga County",
    distance: "25 km from hotel",
    duration: "Half day trip",
    bestTime: "Late afternoon (2:00 PM - 6:00 PM)",
    entryFee: "KES 250 for adults, KES 100 for children",
    highlights: [
      "Cultural significance",
      "Photography",
      "Panoramic views",
      "Local legends",
      "Sunset views",
      "Folklore stories",
    ],
    activities: [
      "Guided tours with folklore storytelling",
      "Panoramic photography sessions",
      "Sunset viewing from the summit",
      "Cultural education about Luhya traditions",
      "Meditation and reflection time",
      "Local craft shopping",
      "Traditional dance performances (weekends)",
    ],
    facilities: [
      "Visitor information center",
      "Parking area",
      "Souvenir shop",
      "Viewing platforms",
      "Picnic area",
    ],
    whatToBring: [
      "Camera with good zoom",
      "Comfortable walking shoes",
      "Hat and sunscreen",
      "Water bottle",
      "Cash for souvenirs",
    ],
    rating: 4.4,
    reviews: 112,
    difficulty: "Easy",
    groupSize: "2-25 people",
  },
  {
    id: "5",
    name: "Masinde Muliro Gardens",
    description:
      "Beautiful botanical gardens featuring diverse plant species, perfect for leisurely walks and family outings.",
    longDescription:
      "Named after the renowned Kenyan politician Masinde Muliro, these botanical gardens serve as both a recreational facility and an educational center for botanical conservation. The gardens showcase over 200 species of indigenous and exotic plants, including medicinal herbs, ornamental flowers, and rare tree species. Well-maintained pathways wind through different themed sections, including a rose garden, herb garden, indigenous tree section, and a children's discovery area. The gardens also feature a small lake with water lilies and provide habitat for various bird species. Educational programs are regularly conducted for schools and community groups, focusing on environmental conservation and sustainable gardening practices.",
    image: "/Muliro Gardens.webp",
    gallery: [
      "/Muliro Gardens.webp",
      "/Customers 13.webp",
      "/Customers 14.webp",
      "/Customers 15.webp",
    ],
    location: "Kakamega Town",
    distance: "40 km from hotel",
    duration: "Half day trip",
    bestTime: "Morning (8:00 AM - 12:00 PM)",
    entryFee: "KES 150 for adults, KES 50 for children",
    highlights: [
      "Botanical diversity",
      "Family friendly",
      "Peaceful walks",
      "Educational tours",
      "Photography",
      "Picnic areas",
    ],
    activities: [
      "Self-guided botanical walks",
      "Educational tours with botanist guides",
      "Photography workshops",
      "Family picnics in designated areas",
      "Children's nature discovery programs",
      "Medicinal plant identification tours",
      "Gardening workshops and demonstrations",
    ],
    facilities: [
      "Visitor center",
      "Gift shop",
      "Picnic areas",
      "Children's playground",
      "Parking",
      "Restrooms",
      "Café",
    ],
    whatToBring: [
      "Comfortable walking shoes",
      "Camera",
      "Notebook for plant identification",
      "Picnic supplies",
      "Sun hat",
    ],
    rating: 4.3,
    reviews: 94,
    difficulty: "Easy",
    groupSize: "2-30 people",
  },
  {
    id: "6",
    name: "Malava Forest",
    description:
      "Indigenous forest reserve offering hiking trails, bird watching opportunities, and a chance to experience Kenya's natural heritage.",
    longDescription:
      "Malava Forest is a pristine indigenous forest reserve that represents one of the last remaining patches of Kenya's original forest cover in Western Kenya. This 2,000-hectare forest is home to over 150 bird species, including several endemic species found nowhere else in Kenya. The forest features well-maintained hiking trails of varying difficulty levels, from easy nature walks suitable for families to challenging treks for experienced hikers. Ancient trees, some over 500 years old, create a cathedral-like canopy that filters sunlight into ethereal beams. The forest plays a crucial role in water catchment for the region and serves as a living laboratory for forest conservation research and community-based forest management programs.",
    image: "/Kakamega Forest.webp", // Using Kakamega Forest image as a suitable substitute
    gallery: [
      "/Kakamega Forest.webp",
      "/Building 7.webp",
      "/KRD03786.webp",
      "/Top View.webp",
    ],
    location: "Kakamega County",
    distance: "50 km from hotel",
    duration: "Full day trip",
    bestTime: "Early morning (6:00 AM - 11:00 AM)",
    entryFee: "KES 400 for adults, KES 200 for children",
    highlights: [
      "Forest hiking",
      "Bird species",
      "Indigenous trees",
      "Conservation education",
      "Photography",
      "Research tours",
    ],
    activities: [
      "Guided forest hiking on multiple trail options",
      "Bird watching with expert ornithologist guides",
      "Tree identification and forest ecology tours",
      "Photography expeditions for wildlife and landscapes",
      "Conservation education programs",
      "Research facility visits",
      "Community forest management demonstrations",
    ],
    facilities: [
      "Research station",
      "Visitor center",
      "Guided tour services",
      "Parking",
      "Basic camping facilities",
      "Restrooms",
    ],
    whatToBring: [
      "Sturdy hiking boots",
      "Binoculars",
      "Camera with telephoto lens",
      "Water and snacks",
      "Rain jacket",
      "Field notebook",
    ],
    rating: 4.7,
    reviews: 78,
    difficulty: "Moderate to Challenging",
    groupSize: "2-10 people",
  },
];
