const rooms = [
  {
    $id: "room1",
    $createdAt: "2025-07-01T10:00:00Z",
    $updatedAt: "2025-07-01T10:00:00Z",
    name: "Standard Queen Room",
    price: 12000,
    beds: 1,
    bathrooms: 1,
    wifi: true,
    tv: true,
    ac: true,
    laundry: false,
    dinner: false,
    images: ["/rooms/standard-queen-1.jpg", "/rooms/standard-queen-2.jpg"],
    shortDescription: "Cozy queen bed room with city view.",
    description:
      "Our Standard Queen Room features a comfortable queen-sized bed, en-suite bathroom, complimentary Wi-Fi, flat-screen TV, and air conditioning. Perfect for solo travelers or couples seeking comfort on a budget.",
    status: "available",
    averageRating: 4.2,
  },
  {
    $id: "room2",
    $createdAt: "2025-07-02T11:30:00Z",
    $updatedAt: "2025-07-02T11:30:00Z",
    name: "Deluxe Double Room",
    price: 18000,
    beds: 2,
    bathrooms: 1,
    wifi: true,
    tv: true,
    ac: true,
    laundry: true,
    dinner: false,
    images: [
      "/rooms/deluxe-double-1.jpg",
      "/rooms/deluxe-double-2.jpg",
      "/rooms/deluxe-double-3.jpg",
    ],
    shortDescription: "Spacious double room with extras.",
    description:
      "Enjoy extra space in our Deluxe Double Room, featuring two double beds, a work desk, en-suite bathroom, high-speed Wi-Fi, flat-screen TV, air conditioning, and complimentary laundry service.",
    status: "available",
    averageRating: 4.6,
  },
  {
    $id: "room3",
    $createdAt: "2025-07-03T09:15:00Z",
    $updatedAt: "2025-07-03T09:15:00Z",
    name: "Executive Suite",
    price: 30000,
    beds: 1,
    bathrooms: 1,
    wifi: true,
    tv: true,
    ac: true,
    laundry: true,
    dinner: true,
    images: [
      "/rooms/executive-suite-1.jpg",
      "/rooms/executive-suite-2.jpg",
      "/rooms/executive-suite-3.jpg",
    ],
    shortDescription: "Roomy suite with dinner included.",
    description:
      "The Executive Suite includes a king-sized bed, separate sitting area, premium toiletries, complimentary dinner for two, laundry service, high-speed Wi-Fi, flat-screen TV, and full air conditioning.",
    status: "available",
    averageRating: 4.9,
  },
  {
    $id: "room4",
    $createdAt: "2025-07-04T14:45:00Z",
    $updatedAt: "2025-07-04T14:45:00Z",
    name: "Family Suite",
    price: 35000,
    beds: 3,
    bathrooms: 2,
    wifi: true,
    tv: true,
    ac: true,
    laundry: true,
    dinner: true,
    images: ["/rooms/family-suite-1.jpg", "/rooms/family-suite-2.jpg"],
    shortDescription: "Perfect for families, sleeps up to 5.",
    description:
      "Our Family Suite offers three beds (one king, two twins), two bathrooms, a living area, complimentary dinner for all guests, laundry service, free Wi-Fi, and multiple TVs with cable.",
    status: "available",
    averageRating: 4.5,
  },
  {
    $id: "room5",
    $createdAt: "2025-07-05T08:20:00Z",
    $updatedAt: "2025-07-05T08:20:00Z",
    name: "Presidential Suite",
    price: 75000,
    beds: 1,
    bathrooms: 2,
    wifi: true,
    tv: true,
    ac: true,
    laundry: true,
    dinner: true,
    images: [
      "/rooms/presidential-1.jpg",
      "/rooms/presidential-2.jpg",
      "/rooms/presidential-3.jpg",
    ],
    shortDescription: "Luxury suite with premium amenities.",
    description:
      "Experience ultimate luxury in our Presidential Suite with a king bed, marble bathrooms, private balcony, in-suite laundry, gourmet dinner, high-speed Wi-Fi, multiple TVs, and 24-hour butler service.",
    status: "available",
    averageRating: 5.0,
  },
  {
    $id: "room6",
    $createdAt: "2025-07-06T12:10:00Z",
    $updatedAt: "2025-07-06T12:10:00Z",
    name: "Standard Twin Room",
    price: 13000,
    beds: 2,
    bathrooms: 1,
    wifi: true,
    tv: true,
    ac: true,
    laundry: false,
    dinner: false,
    images: ["/rooms/standard-twin-1.jpg", "/rooms/standard-twin-2.jpg"],
    shortDescription: "Comfortable twin beds with amenities.",
    description:
      "Ideal for friends or colleagues, the Standard Twin Room features two single beds, en-suite bathroom, complimentary Wi-Fi, flat-screen TV, and air conditioning.",
    status: "available",
    averageRating: 4.1,
  },
  {
    $id: "room7",
    $createdAt: "2025-07-07T16:00:00Z",
    $updatedAt: "2025-07-07T16:00:00Z",
    name: "Deluxe King Room",
    price: 20000,
    beds: 1,
    bathrooms: 1,
    wifi: true,
    tv: true,
    ac: true,
    laundry: true,
    dinner: false,
    images: ["/rooms/deluxe-king-1.jpg", "/rooms/deluxe-king-2.jpg"],
    shortDescription: "King bed with deluxe comforts.",
    description:
      "Relax in our Deluxe King Room, featuring a spacious king-sized bed, modern en-suite, laundry service, free Wi-Fi, flat-screen TV, and air conditioning.",
    status: "available",
    averageRating: 4.4,
  },
  {
    $id: "room8",
    $createdAt: "2025-07-08T07:50:00Z",
    $updatedAt: "2025-07-08T07:50:00Z",
    name: "Economy Single Room",
    price: 9000,
    beds: 1,
    bathrooms: 1,
    wifi: true,
    tv: false,
    ac: false,
    laundry: false,
    dinner: false,
    images: ["/rooms/economy-single-1.jpg"],
    shortDescription: "Basic single room, budget-friendly.",
    description:
      "The Economy Single Room provides a single bed, en-suite bathroom, complimentary Wi-Fi, and essential comforts for budget-minded travelers.",
    status: "available",
  },
  {
    $id: "room9",
    $createdAt: "2025-07-09T13:25:00Z",
    $updatedAt: "2025-07-09T13:25:00Z",
    name: "Junior Suite",
    price: 25000,
    beds: 1,
    bathrooms: 1,
    wifi: true,
    tv: true,
    ac: true,
    laundry: true,
    dinner: true,
    images: ["/rooms/junior-suite-1.jpg", "/rooms/junior-suite-2.jpg"],
    shortDescription: "Chic suite with lounge area.",
    description:
      "The Junior Suite offers a king bed, comfortable lounge space, en-suite bathroom, complimentary dinner, laundry service, Wi-Fi, TV, and AC.",
    status: "available",
    averageRating: 4.7,
  },
  {
    $id: "room10",
    $createdAt: "2025-07-10T15:40:00Z",
    $updatedAt: "2025-07-10T15:40:00Z",
    name: "Accessible Room",
    price: 15000,
    beds: 1,
    bathrooms: 1,
    wifi: true,
    tv: true,
    ac: true,
    laundry: false,
    dinner: false,
    images: ["/rooms/accessible-1.jpg", "/rooms/accessible-2.jpg"],
    shortDescription: "Wheelchair-friendly accessible room.",
    description:
      "Our Accessible Room features widened doorways, roll-in shower, grab rails, king bed, Wi-Fi, TV, and air conditioning to ensure comfort for all guests.",
    status: "available",
    averageRating: 4.3,
  },
];
